name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Backend - Install dependencies
        run: |
          cd backend
          npm install

      - name: Backend - Run tests
        run: |
          cd backend
          npm test

      - name: Frontend - Install dependencies
        run: |
          cd frontend
          npm install

      - name: Frontend - Run tests
        run: |
          cd frontend
          npm test -- --watchAll=false

      - name: Cypress E2E Tests
        run: |
          npx cypress run
        working-directory: frontend
